### ISSUE TITLE
Elasticsearch cluster members all try to bind to the same IP address

### ISSUE THREAD

**Issue by soleger** [j-white/opennms-minion-aws#2]
The ```network.host``` for Elasticsearch is always set to the same IP address for every member of the auto scaling group which means that the bind will fail on every host except the first one in the group:

https://github.com/j-white/opennms-minion-aws/blob/master/roles/elasticsearch/templates/elasticsearch.yml.tpl#L58

The ```network.host``` should probably be set to ```0.0.0.0``` instead to bind to all interfaces.

**Comment by j-white** [comment]
Fixed with https://github.com/j-white/opennms-minion-aws/commit/38eb2c94fc572baea3e099005e5ec39da7608cae
